### ISSUE TITLE
Move diffusion to top level menu

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/diffusion#3]
Currently, Diffusion is available under the Apps sub-menu of the context menu. It should be moved into the context menu itself ... at the same level as Apps.

**Comment by keiono** [comment]
Fixed by adding PREFFERED_MENU prop.

**Comment by bdemchak** [comment]
"Diffusion" -> "Diffuse" ... this portion of the menu uses verbs. I suspect Trey would like to have it between Groups and Nested Networks ... can we move this to there??

**Comment by keiono** [comment]
This is controlled by the core, and there is no way to move the position because the context menu is  created with a static values coded in Ding implementation.

**Comment by bdemchak** [comment]
This will not pass Trey's review, and it doesn't give good attention to the importance of this feature. A technical convenience isn't a reason for a feature. This issue should be left open until either Trey agrees that it's OK to let the core bury it.

**Comment by keiono** [comment]
OK, in any case, the only way to enable this is moving this code to the core, *NOT CORE APP*.  This menu item is managed by low level rendering code, and even core app cannot change it.

And by the group agreement, editing that top level menu item is not allowed.  We need to convince others first to make this change because it breaks context menu consistency.

**Comment by bdemchak** [comment]
Better that than to have Trey and users reject the app.
